name: 🪞 Mirror to Codeberg
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 0' # At 03:30 on Sunday
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: lissy93/repo-mirror-action@v1.5.0
        with:
          ssh_key: ${{ secrets.CODEBERG_SSH }}
          host: git@codeberg.org
          user: alicia
          repo: as93
          force_push: false
